# curl -X GET https://graph.facebook.com/v10.0/me?access_token=EAAG1sA34FykBABpXwTOFjwZBLyiY0Vwi4MZB51q8N4aagBckNTKVkERpF0bLS4zfx4p2AGlkmYZCzquJwrMTJY6WufFsQD6KZBc87uXyb39oLIDff9UItvVc9BUzvgv961seaNbM6ASbuFmxlpZAmcBWHbdDYFtYV6xJR2JX1Awny1YhFWzbBS02ZBZA6WaCq2PKhTKcgG3ZANivSOJOcig2IM3pSpYkfBKtQZAPWVZAEiXnNIP51Gesw2



GET https://graph.facebook.com/v10.0/me/accounts?fields=name,category,category_list&access_token=EAAG1sA34FykBABpXwTOFjwZBLyiY0Vwi4MZB51q8N4aagBckNTKVkERpF0bLS4zfx4p2AGlkmYZCzquJwrMTJY6WufFsQD6KZBc87uXyb39oLIDff9UItvVc9BUzvgv961seaNbM6ASbuFmxlpZAmcBWHbdDYFtYV6xJR2JX1Awny1YhFWzbBS02ZBZA6WaCq2PKhTKcgG3ZANivSOJOcig2IM3pSpYkfBKtQZAPWVZAEiXnNIP51Gesw2