name: shoplive_mvp
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  http: ^0.12.2
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  logger: ^1.0.0
  # flutter_screenutil: ^5.0.0
  # states_rebuilder: ^4.0.0+1
  # flutter_facebook_login:
  multi_select_flutter: ^4.0.0
  awesome_dialog: ^1.3.2
  visa:
    path: ./external/visa
  # flutter_event_bus: ^0.0.2
  font_awesome_flutter: ^9.0.0
  rtmp_publisher: ^0.3.7
  flutter_inappwebview: ^4.0.0
  permission_handler: ^7.1.0
    # path: ../
  # camera:
  path_provider:
 
  video_player: ^0.10.11
  e2e: ^0.4.2
  wakelock: ^0.1.4+1

  # flutter_facebook_auth: ^3.3.3-no-nullsafety
  # google_sign_in: ^5.0.2
  # flutter_login_facebook:
  # flutter_login_facebook: ^1.2.0
  # http: ^0.13.1
  flutter_webview_plugin:
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/

  # fonts:
  #   - family: CustomIcons
  #     fonts:
  #       - asset: assets/CustomIcons.ttf

  #   - family: Poppins-Bold
  #     fonts:
  #       - asset: assets/Poppins-Bold.ttf

  #   - family: Poppins-Medium
  #     fonts:
  #       - asset: assets/Poppins-Medium.ttf    

  # To add assets to your application, add an assets section, like this:

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
